# golangci-lint configuration for ORCA
# Pragmatic linting - catch real issues, avoid noise

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - errcheck      # Unchecked errors
    - gosimple      # Simplify code
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type checking
    - unused        # Unused code
    - gofmt         # Formatting
    - goimports     # Import formatting
    - misspell      # Spell checker
    - gocritic      # Comprehensive checks
    - gosec         # Security issues
    - revive        # Replacement for golint
    - errname       # Error naming conventions
    - errorlint     # Error wrapping issues
    - gocyclo       # Cyclomatic complexity
    - dupl          # Duplicate code
    - bodyclose     # HTTP body close
    - noctx         # HTTP requests without context

  disable:
    - exhaustive    # Too noisy for switches
    - exhaustruct   # Too strict for struct initialization
    - gomnd         # Magic numbers - too strict
    - nlreturn      # Return formatting - personal preference
    - wsl           # Whitespace - too opinionated
    - funlen        # Function length - we'll judge ourselves
    - lll           # Line length - gofmt handles this

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15  # Reasonable complexity limit

  dupl:
    threshold: 100  # Lines of duplicate code to trigger

  gosec:
    excludes:
      - G104  # Audit errors - covered by errcheck
      - G304  # File inclusion - we control inputs
    config:
      G306: "0644"  # File permissions

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentFormatting  # Too strict
      - whyNoLint         # Covered by other linters

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - dupl

    # Exclude generated code
    - path: ".*\\.pb\\.go$"
      linters:
        - all

    # Exclude mock files
    - path: mock.*\.go
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
