name: 📚 Documentation
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve ORCA's documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - Getting Started / Quick Start
        - User Guide
        - Architecture Documentation
        - API Reference (Annotations, Config)
        - Development / Contributing
        - Examples / Tutorials
        - README
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What's wrong with the documentation?
      options:
        - Missing Documentation
        - Incorrect/Outdated Information
        - Unclear/Confusing Explanation
        - Broken Links
        - Typo/Grammar
        - Missing Examples
        - Needs Diagram/Visual
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Page/Section
      description: Which page or section needs improvement?
      placeholder: docs/user-guide/gpu-workloads.md

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say (or not say)?
      placeholder: The current docs state...

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: What should the documentation say instead?
      placeholder: It should explain...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Why This Matters
      description: How would this improvement help users?
      placeholder: This would help researchers understand...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Suggested Example (Optional)
      description: If you have a specific example or code snippet to add
      render: yaml

  - type: dropdown
    id: volunteer
    attributes:
      label: Would you like to contribute this fix?
      description: We welcome documentation contributions!
      options:
        - "Yes, I can submit a PR"
        - "Maybe, with guidance"
        - "No, just reporting"
    validations:
      required: true
