name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Before submitting, please check:
        - Does this align with ORCA's research-first design principles?
        - Have you searched existing issues to avoid duplicates?

  - type: dropdown
    id: use-case
    attributes:
      label: Research Use Case
      description: What research computing scenario does this help?
      options:
        - AI/ML Training (GPUs)
        - AI/ML Inference
        - Custom Silicon (Trainium/Inferentia/FPGA)
        - Batch Processing
        - Cost Optimization
        - Multi-tenancy/Quotas
        - Research Platform Integration (NRP)
        - General Research Computing
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of ORCA would this affect?
      options:
        - Virtual Kubelet Provider
        - Instance Selection
        - AWS Integration
        - Pod Lifecycle
        - Cost Management
        - Monitoring/Metrics
        - Configuration
        - Documentation
        - All Components
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a research computing administrator, I need to [do something] because [reason]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        I'd like ORCA to support...
        For example, add annotation: `orca.research/new-feature: "value"`
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other ways to solve this problem?
      placeholder: I also considered...

  - type: textarea
    id: workflow
    attributes:
      label: Example Workflow
      description: Show us how this feature would improve your workflow
      placeholder: |
        Current workflow:
        1. Manually configure...
        2. Wait for...

        With this feature:
        1. Simply annotate pod...
        2. ORCA automatically...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your research?
      options:
        - Critical - Blocking research work
        - High - Would significantly improve workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require breaking changes to existing functionality?
      options:
        - No breaking changes
        - Minor breaking changes (with migration path)
        - Major breaking changes
        - Not sure
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information, examples, or references
      placeholder: Links to similar features in other tools, research papers, AWS documentation, etc.
