---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orca-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: orca
      app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/scttfrdmn/orca
    newTag: latest
