---
apiVersion: v1
kind: Service
metadata:
  name: orca-metrics
  namespace: orca-system
  labels:
    app.kubernetes.io/name: orca
    app.kubernetes.io/component: virtual-kubelet
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: orca
    app.kubernetes.io/component: virtual-kubelet
