#!/bin/bash
# Script to help set up GitHub Project for ORCA

set -e

REPO="scttfrdmn/orca"
PROJECT_NUMBER=3

echo "🎯 GitHub Project Setup for ORCA"
echo "================================"
echo ""
echo "✅ Project created: ORCA Development (Project #$PROJECT_NUMBER)"
echo ""
echo "📋 Next Steps (Manual via Web UI):"
echo ""
echo "1. Link Project to Repository:"
echo "   → Go to: https://github.com/$REPO/settings"
echo "   → Scroll to 'Features' section"
echo "   → Find 'Projects' and click 'Link a project'"
echo "   → Select 'ORCA Development' from dropdown"
echo "   → Click 'Link project'"
echo ""
echo "2. Configure Project Board:"
echo "   → Go to: https://github.com/users/scttfrdmn/projects/$PROJECT_NUMBER"
echo "   → Click '⋯' (menu) → Settings"
echo "   → Add custom fields:"
echo "     • Priority: Single select (Critical, High, Medium, Low)"
echo "     • Area: Single select (Provider, AWS, Instances, Config, Docs, Tests)"
echo "     • Use Case: Single select (GPU Training, Inference, Cost Optimization, etc.)"
echo ""
echo "3. Set Up Workflow Automation:"
echo "   → In project, click '⋯' → Workflows"
echo "   → Enable these automations:"
echo "     ✓ Item added to project → Set status to 'Todo'"
echo "     ✓ Item closed → Set status to 'Done'"
echo "     ✓ Pull request merged → Set status to 'Done'"
echo "     ✓ Item reopened → Set status to 'Todo'"
echo ""
echo "4. Create Project Views:"
echo "   → Board view (default)"
echo "   → Table view: All items"
echo "   → Table view: By Priority"
echo "   → Board view: By Area"
echo ""
echo "5. Add Initial Issues to Project:"
echo "   → Create issues with: gh issue create --repo $REPO"
echo "   → Add to project: In issue, click 'Projects' on right sidebar"
echo "   → Select 'ORCA Development'"
echo ""
echo "📝 Recommended Initial Issues:"
echo ""
echo "MVP Critical:"
echo "  • Container runtime integration"
echo "  • kubectl logs support (CloudWatch)"
echo "  • kubectl exec support (Systems Manager)"
echo "  • GPU capacity reservations"
echo ""
echo "Documentation:"
echo "  • Complete getting started guide"
echo "  • Add architecture diagrams"
echo "  • Create GPU workload examples"
echo ""
echo "Good First Issues:"
echo "  • Add more unit tests"
echo "  • Improve error messages"
echo "  • Add godoc comments"
echo ""
echo "🔗 Quick Links:"
echo "   Project: https://github.com/users/scttfrdmn/projects/$PROJECT_NUMBER"
echo "   Repo:    https://github.com/$REPO"
echo "   Issues:  https://github.com/$REPO/issues"
echo ""
echo "💡 After setup, issues will automatically appear in project board!"
